name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest

      - name: Install dependencies
        run: uvx just install-dev

      - name: Run linting
        run: uvx just lint

      - name: Run tests
        run: uvx just test

      - name: Run the main script
        run: uvx just run
